# CI Pipeline

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Git
      run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}

    - name: Get the latest tag
      id: get-latest-tag
      run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV

    - name: Calculate new tag
      id: calculate-new-tag
      run: |
          current_tag=${tag/v/}
          IFS='.' read -ra parts <<< "$current_tag"
          parts[2]=$((parts[2] + 1))
          new_tag="v${parts[0]}.${parts[1]}.${parts[2]}"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

    - name: Create new tag
      run: |
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven

    - name: Update version in pom.xml (optional)
      run: mvn versions:set -DnewVersion=${{ env.NEW_VERSION }}-auth-service

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: miguelacs/personal:${{ env.new_tag }}-auth-service
