# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Fetch all tags from remote
      run: git fetch --tags

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven

    - name: Get current version from git tag
      id: get_version
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0)
        VERSION_NUMBER=$(echo $LAST_TAG | sed -E 's/([0-9]+\.[0-9]+\.[0-9]+)-auth-service/\1/')
        VERSION_PARTS=(${VERSION_NUMBER//./ })
        PATCH=${VERSION_PARTS[2]}
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH"
        echo "NEW_VERSION=$NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Update version in pom.xml (optional)
      run: |
        mvn versions:set -DnewVersion=${{ env.NEW_VERSION }}-auth-service

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: miguelacs/personal:${{ env.NEW_VERSION }}-auth-service
