# CI Pipeline For Updating Tag, Build with Maven, Build the Image 
# and Pushes the Image to Dockerhub

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Updates Tag
      id: autotagger
      uses: phish108/autotag-action@v1.1.55
      with:
        github-token: ${{ secrets.GH_TOKEN}}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push to Dockerhub
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: miguelacs/personal:${{ steps.autotagger.outputs.new-tag }}-auth-service

    - name: Checkout deployment repository
      run: |
        git clone https://github.com/MiguelCastilloSanchez/helm-chart-auth-service.git
        cd helm-chart-auth-service

    - name: Update image tag in values.yaml
      run: |
        new_tag="${{ steps.autotagger.outputs.new-tag }}-auth-service"
        sed -i "s/tag: .*/tag: \"${new_tag}\"/" values.yaml

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git add values.yaml
        git commit -m "Update image tag to ${{ steps.autotagger.outputs.new-tag }}-auth-service #patch"
        git push https://<user>:${{ secrets.GH_TOKEN }}@github.com/<user>/<target-repo>.git
